;/* âπêF */

tone_table0:
;		/* 0 */
db		 113,  97, 102,  10,  48,  66,  45,  59

tone_table1:
;		/* 1 */
db		 117, 113, 101,  74, 128,  96,   7,  14

tone_table2:
;		/* 2 */
db		   5,   1,  24,  13, 170, 250,  39,  21

tone_table3:
;		/* 3 */
db		 241,  33,  86,  24, 209, 241,  39,  24

tone_table4:
;		/* 4 */
db		0

tone_table:
dw	tone_table0, tone_table1, tone_table2, tone_table3, tone_table4
